# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        # Docker Hub image
        image: postgres:16
        # Provide the password for postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: simple_bank
        # Set health checks to wait until postgres has started need it for tests to pass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
  

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.3
    
    - name: Check out code into Go module directory
      uses: actions/checkout@v2

        # need to install migrate cli from github so this image can use migrate command
        # mv the migrate into usr/bin. found filename by running command locally
    - name: Install Migrate CLI
      run: | 
        curl -L hhttps://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/
        which migrate

    - name: Run Migrations
      run: make migrateup #define schema for db

    - name: Test
      run: make test
